import { DashboardData, ChecklistTemplate } from '../types';

export const BUILT_IN_TEMPLATES: ChecklistTemplate[] = [
  {
    id: 'tpl-interview-prep',
    name: 'Interview Preparation',
    description: 'Comprehensive pre-interview readiness checklist',
    category: 'Preparation',
    isBuiltIn: true,
    defaultItems: [
      { title: 'Company research & product offerings', priority: 'High', description: 'Understand mission, clients, tech stack, and recent news' },
      { title: 'Job description review & key requirements alignment', priority: 'High', description: 'Map your skills to each requirement in the JD' },
      { title: 'Resume review & project story recap', priority: 'High', description: 'Be ready to explain any point on your resume' },
      { title: 'Self introduction practice (Elevator Pitch)', priority: 'High', description: 'Practice a punchy 90-second intro focusing on your MERN expertise' },
      { title: 'Project explanation (Architecture, challenges, solutions)', priority: 'High', description: 'Deep dive into FarmGuard, Cartify, and Vendr' },
      { title: 'Technical preparation & core concepts', priority: 'High', description: 'Async JS, Event Loop, React Lifecycle, Node streams, indexing' },
      { title: 'Expected questions & behavioral stories (STAR method)', priority: 'Medium', description: 'Prepare for conflict resolution, leadership, and debugging scenarios' },
      { title: 'Questions for interviewer (Role, engineering culture, tech debt)', priority: 'Medium', description: 'Prepare 3-4 insightful questions' },
      { title: 'Salary discussion preparation & market rates', priority: 'Low', description: 'Know your minimum acceptable and target range' },
      { title: 'Interview setup check (Laptop, mic, camera, quiet space)', priority: 'High', description: 'Test Zoom/Meet 30 minutes before time' },
    ],
  },
  {
    id: 'tpl-technical-interview-mern',
    name: 'Technical Interview (MERN Stack)',
    description: 'Targeted technical revision checklist tailored to JavaScript, TypeScript, React, and Node.js',
    category: 'Technical',
    isBuiltIn: true,
    defaultItems: [
      { title: 'JavaScript fundamentals (Closures, Prototype, Event Loop, Promises, Async/Await)', priority: 'High' },
      { title: 'TypeScript (Generics, Interfaces vs Types, Utility types, Type Narrowing)', priority: 'High' },
      { title: 'React (Hooks, Custom Hooks, Context, Reconciliation, Memoization, State management)', priority: 'High' },
      { title: 'Node.js & Express (Event-driven architecture, Middleware, Streams, Clustering, Error handling)', priority: 'High' },
      { title: 'REST APIs & Best Practices (Status codes, Versioning, Idempotency, Rate limiting)', priority: 'High' },
      { title: 'Authentication & Security (JWT, Refresh tokens, OAuth, CORS, SQL/NoSQL injection prevention)', priority: 'High' },
      { title: 'MongoDB & Mongoose (Aggregations, Schema design, Indexing performance, Sharding basics)', priority: 'High' },
      { title: 'MySQL & Relational DBs (ACID properties, Joins, Normalization, Query optimization)', priority: 'Medium' },
      { title: 'Redis & BullMQ (Caching strategies, Pub/Sub, Queue processing, Rate limiting)', priority: 'Medium' },
      { title: 'Coding Practice (Arrays, Strings, Hash maps, Two pointers, Recursion)', priority: 'High' },
      { title: 'System Design Basics (Scalability, Load balancing, Microservices vs Monolith, CDN)', priority: 'Medium' },
      { title: 'Project Deep Dive: FarmGuard & Cartify architectures', priority: 'High' },
    ],
  },
  {
    id: 'tpl-hr-interview',
    name: 'HR & Behavioral Interview',
    description: 'Key behavioral questions and cultural fit evaluation',
    category: 'HR',
    isBuiltIn: true,
    defaultItems: [
      { title: 'Why do you want to join this company?', priority: 'High' },
      { title: 'Why are you looking for a change / next career step?', priority: 'High' },
      { title: 'Strengths and areas of growth with real examples', priority: 'Medium' },
      { title: 'Time when you handled a difficult deadline or production bug', priority: 'High' },
      { title: 'Handling disagreement with team member or manager', priority: 'Medium' },
      { title: 'Notice period, current CTC, expected CTC, and location flexibility', priority: 'High' },
      { title: 'Inquiring about company culture, team hierarchy, and mentorship', priority: 'Medium' },
    ],
  },
  {
    id: 'tpl-before-applying',
    name: 'Before Applying Checklist',
    description: 'Pre-flight check before clicking Submit on any job portal',
    category: 'Application',
    isBuiltIn: true,
    defaultItems: [
      { title: 'Tailor resume keywords to job description', priority: 'High' },
      { title: 'Verify GitHub repositories and live demo links are online', priority: 'High' },
      { title: 'Check LinkedIn profile headline and experience alignment', priority: 'Medium' },
      { title: 'Identify recruiter or team lead on LinkedIn for referral message', priority: 'Medium' },
      { title: 'Prepare customized cover note or cold message', priority: 'Medium' },
      { title: 'Track in CareerHub dashboard immediately', priority: 'High' },
    ],
  },
];

const getTodayDateString = (): string => {
  const d = new Date();
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
};

const getFutureDateString = (daysAhead: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + daysAhead);
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
};

export const getInitialSeedData = (): DashboardData => {
  const todayStr = getTodayDateString();
  const tomorrowStr = getFutureDateString(1);
  const nextWeekStr = getFutureDateString(7);

  return {
    version: 1,
    lastUpdated: new Date().toISOString(),
    userProfile: {
      name: 'Full Stack Engineer',
      title: 'Full Stack Developer (MERN)',
      summary: 'Experienced with JavaScript, TypeScript, React, Node.js, Express, MongoDB, MySQL, Redis, BullMQ, and Docker.',
      skills: {
        languages: ['JavaScript', 'TypeScript', 'SQL', 'HTML5', 'CSS3'],
        frontend: ['React.js', 'Tailwind CSS', 'Bootstrap'],
        backend: ['Node.js', 'Express.js', 'REST APIs', 'JWT Authentication', 'BullMQ'],
        databases: ['MongoDB', 'MySQL', 'Redis', 'Mongoose'],
        cloudAndTools: ['AWS Basics', 'Docker', 'Git', 'GitHub', 'Postman', 'MongoDB Compass', 'Vercel', 'Render', 'npm'],
      },
      projects: [
        'FarmGuard — Agricultural Monitoring System',
        'Cartify — E-Commerce Marketplace',
        'Vendr — Full Stack E-Commerce Platform',
        'Smart Exam Proctoring System',
      ],
    },
    roles: [
      { id: 'role-fullstack', name: 'Full Stack Developer', order: 1, createdAt: new Date().toISOString() },
      { id: 'role-react', name: 'React Developer', order: 2, createdAt: new Date().toISOString() },
      { id: 'role-nodejs', name: 'Node.js Developer', order: 3, createdAt: new Date().toISOString() },
      { id: 'role-backend', name: 'Backend Engineer', order: 4, createdAt: new Date().toISOString() },
    ],
    applications: [
      {
        id: 'app-be-eng',
        roleId: 'role-fullstack',
        company: 'BE Engineer',
        jobTitle: 'Senior Full Stack Developer',
        location: 'Chennai',
        locationType: 'Hybrid',
        appliedDate: getTodayDateString(),
        appliedThrough: 'LinkedIn',
        jobUrl: 'https://linkedin.com/jobs/view/be-engineer',
        status: 'Interview Call',
        interviewDate: tomorrowStr,
        interviewStage: 'Technical',
        recruiterName: 'Ananya Sharma',
        recruiterContact: '+91 98765 43210',
        recruiterLinkedIn: 'https://linkedin.com/in/ananya-recruiter',
        salary: '₹12 - 16 LPA',
        priority: 'High',
        nextAction: 'Revise Node streams, BullMQ queues, and React 18 memoization',
        followUpDate: tomorrowStr,
        notes: 'Team builds scalable SaaS products. Impressed with Cartify and FarmGuard architecture in resume.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'app-abc-tech',
        roleId: 'role-fullstack',
        company: 'ABC Technologies',
        jobTitle: 'MERN Stack Engineer',
        location: 'Bangalore',
        locationType: 'On-site',
        appliedDate: getFutureDateString(-4),
        appliedThrough: 'Naukri',
        jobUrl: 'https://naukri.com/job/abc-tech-mern',
        status: 'Applied',
        recruiterName: 'Rohan Verma',
        recruiterContact: 'rohan.v@abctech.com',
        salary: '₹10 - 14 LPA',
        priority: 'Medium',
        nextAction: 'Follow up on LinkedIn if no response by Friday',
        followUpDate: getFutureDateString(3),
        notes: 'Enterprise client projects using React, Node.js, and MySQL.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'app-xyz-sol',
        roleId: 'role-fullstack',
        company: 'XYZ Solutions',
        jobTitle: 'Full Stack Engineer',
        location: 'Remote',
        locationType: 'Remote',
        appliedDate: getFutureDateString(-12),
        appliedThrough: 'Indeed',
        jobUrl: 'https://indeed.com/xyz-sol',
        status: 'Rejected',
        priority: 'Low',
        notes: 'Position closed due to internal promotion. Sent polite note thanking recruiter.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'app-comp-a',
        roleId: 'role-react',
        company: 'Company A',
        jobTitle: 'Frontend React Specialist',
        location: 'Chennai',
        locationType: 'Hybrid',
        appliedDate: getFutureDateString(-2),
        appliedThrough: 'LinkedIn',
        jobUrl: 'https://companya.io/careers',
        status: 'Applied',
        salary: '₹10 - 13 LPA',
        priority: 'Medium',
        nextAction: 'Check portal status next Monday',
        notes: 'Focus on high-speed consumer UI, Tailwind CSS, TypeScript.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'app-comp-b',
        roleId: 'role-react',
        company: 'Company B',
        jobTitle: 'React / Frontend Developer',
        location: 'Bangalore',
        locationType: 'Remote',
        appliedDate: getFutureDateString(-6),
        appliedThrough: 'Company Website',
        jobUrl: 'https://companyb.com/jobs/react-dev',
        status: 'Interview',
        interviewDate: getFutureDateString(2),
        interviewStage: 'Coding',
        recruiterName: 'Priya Nair',
        recruiterContact: 'priya@companyb.com',
        salary: '₹12 - 15 LPA',
        priority: 'High',
        nextAction: 'Practice live coding React state & custom hook components',
        notes: 'Completed initial screening with flying colors.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'app-innovate-node',
        roleId: 'role-nodejs',
        company: 'NovaStack Labs',
        jobTitle: 'Node.js Backend Developer',
        location: 'Hyderabad',
        locationType: 'Hybrid',
        appliedDate: getFutureDateString(-1),
        appliedThrough: 'Referral',
        jobUrl: 'https://novastack.ai/careers',
        status: 'Applied',
        priority: 'High',
        salary: '₹13 - 17 LPA',
        notes: 'Referred by college senior. High throughput microservices with Express and Redis.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }
    ],
    interviews: [
      {
        id: 'int-be-eng-tech',
        company: 'BE Engineer',
        role: 'Senior Full Stack Developer',
        applicationId: 'app-be-eng',
        interviewDate: tomorrowStr,
        interviewTime: '11:00 AM',
        interviewStage: 'Technical',
        interviewType: 'Video',
        interviewer: 'Siddharth Mehta (Engineering Lead)',
        meetingLink: 'https://meet.google.com/xyz-qwer-asd',
        recruiter: 'Ananya Sharma',
        preparationStatus: 'In Progress',
        questionsAsked: '',
        myAnswers: '',
        mistakes: '',
        feedback: '',
        result: 'Upcoming',
        nextRound: 'Managerial & Cultural Fit',
        nextAction: 'Join meeting 5 mins early; test microphone and video',
        notes: 'Review FarmGuard real-time IoT architecture and BullMQ job processing',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'int-comp-b-round1',
        company: 'Company B',
        role: 'React Developer',
        applicationId: 'app-comp-b',
        interviewDate: getFutureDateString(-3),
        interviewTime: '03:30 PM',
        interviewStage: 'Screening',
        interviewType: 'Phone',
        interviewer: 'Priya Nair (HR & Talent Partner)',
        preparationStatus: 'Completed',
        questionsAsked: 'Discussed past projects (Cartify), notice period, and technical depth in React.',
        myAnswers: 'Walked through component hierarchy, custom hooks, and Tailwind CSS responsive design.',
        mistakes: 'Could have been slightly more concise on state management choices.',
        feedback: 'Very positive feedback, moved quickly to live coding round.',
        result: 'Passed',
        nextRound: 'Live React Coding Challenge',
        nextAction: 'Prepare for round 2 on ' + getFutureDateString(2),
        notes: 'Priya mentioned the team is very collaborative and engineering-driven.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    checklists: [
      {
        id: 'chk-before-applying',
        name: 'Before Applying',
        type: 'Application',
        dueDate: nextWeekStr,
        items: [
          { id: 'c1', title: 'Tailor resume keywords to job description', completed: true, priority: 'High' },
          { id: 'c2', title: 'Verify GitHub repositories and live demo links are online', completed: true, priority: 'High' },
          { id: 'c3', title: 'Check LinkedIn profile headline and experience alignment', completed: true, priority: 'Medium' },
          { id: 'c4', title: 'Identify recruiter or team lead on LinkedIn for referral message', completed: true, priority: 'Medium' },
          { id: 'c5', title: 'Prepare customized cover note or cold message', completed: false, priority: 'Medium' },
          { id: 'c6', title: 'Track in CareerHub dashboard immediately', completed: false, priority: 'High' },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'chk-interview-prep',
        name: 'Interview Preparation',
        type: 'Preparation',
        dueDate: tomorrowStr,
        items: [
          { id: 'p1', title: 'Company research & product offerings', completed: true, priority: 'High' },
          { id: 'p2', title: 'Job description review & key requirements alignment', completed: true, priority: 'High' },
          { id: 'p3', title: 'Resume review & project story recap', completed: true, priority: 'High' },
          { id: 'p4', title: 'Self introduction practice (Elevator Pitch)', completed: true, priority: 'High' },
          { id: 'p5', title: 'Project explanation (Architecture, challenges, solutions)', completed: true, priority: 'High' },
          { id: 'p6', title: 'Technical preparation & core concepts', completed: true, priority: 'High' },
          { id: 'p7', title: 'Expected questions & behavioral stories (STAR method)', completed: true, priority: 'Medium' },
          { id: 'p8', title: 'Questions for interviewer (Role, engineering culture)', completed: false, priority: 'Medium' },
          { id: 'p9', title: 'Salary discussion preparation & market rates', completed: false, priority: 'Low' },
          { id: 'p10', title: 'Interview setup check (Laptop, mic, quiet space)', completed: false, priority: 'High' },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'chk-technical-interview',
        name: 'Technical Interview (MERN)',
        type: 'Technical',
        dueDate: nextWeekStr,
        items: [
          { id: 't1', title: 'JavaScript (Closures, Event Loop, Promises, Async/Await)', completed: true, priority: 'High' },
          { id: 't2', title: 'TypeScript (Generics, Interfaces vs Types, Narrowing)', completed: true, priority: 'High' },
          { id: 't3', title: 'React (Hooks, Custom Hooks, Context, Memoization)', completed: true, priority: 'High' },
          { id: 't4', title: 'Node.js & Express (Event-driven architecture, Middleware, Streams)', completed: true, priority: 'High' },
          { id: 't5', title: 'REST APIs & Best Practices (Status codes, Versioning)', completed: true, priority: 'High' },
          { id: 't6', title: 'Authentication (JWT, Refresh tokens, OAuth, Security)', completed: true, priority: 'High' },
          { id: 't7', title: 'MongoDB & Mongoose (Aggregations, Schema design, Indexing)', completed: true, priority: 'High' },
          { id: 't8', title: 'MySQL & Relational DBs (ACID, Joins, Normalization)', completed: true, priority: 'Medium' },
          { id: 't9', title: 'Redis & BullMQ (Caching strategies, Pub/Sub, Queues)', completed: true, priority: 'Medium' },
          { id: 't10', title: 'Coding Practice (Arrays, Strings, Hash maps, Two pointers)', completed: true, priority: 'High' },
          { id: 't11', title: 'Project Deep Dive: FarmGuard & Cartify architectures', completed: true, priority: 'High' },
          { id: 't12', title: 'Docker basics & Deployment workflow (Vercel/Render)', completed: true, priority: 'Medium' },
          { id: 't13', title: 'System Design: Scalability & Load balancing basics', completed: false, priority: 'Medium' },
          { id: 't14', title: 'GraphQL vs REST comparison notes', completed: false, priority: 'Low' },
          { id: 't15', title: 'Microservices communication patterns', completed: false, priority: 'Low' },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'chk-hr-round',
        name: 'HR Interview',
        type: 'HR',
        items: [
          { id: 'h1', title: 'Why do you want to join this company?', completed: true, priority: 'High' },
          { id: 'h2', title: 'Why are you looking for a change / next career step?', completed: true, priority: 'High' },
          { id: 'h3', title: 'Strengths and areas of growth with real examples', completed: true, priority: 'Medium' },
          { id: 'h4', title: 'Time when you handled a difficult deadline or production bug', completed: true, priority: 'High' },
          { id: 'h5', title: 'Notice period, current CTC, and expected CTC', completed: true, priority: 'High' },
          { id: 'h6', title: 'Handling disagreement with team member or manager', completed: false, priority: 'Medium' },
          { id: 'h7', title: 'Inquiring about company culture, team hierarchy', completed: false, priority: 'Medium' },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    checklistTemplates: BUILT_IN_TEMPLATES,
    dayChecklists: [
      {
        id: 'day-chk-today',
        date: todayStr,
        title: 'BE Engineer Interview Day',
        recurrence: 'one-time',
        tasks: [
          { id: 'dt-1', title: 'Review company background & tech stack', completed: true },
          { id: 'dt-2', title: 'Review JD & align talking points', completed: true },
          { id: 'dt-3', title: 'Revise React (Hooks, state management, reconciliation)', completed: true },
          { id: 'dt-4', title: 'Revise Node.js (Event loop, streams, middleware)', completed: false },
          { id: 'dt-5', title: 'Review project explanation (FarmGuard & Cartify)', completed: false },
          { id: 'dt-6', title: 'Prepare interviewer questions', completed: false },
          { id: 'dt-7', title: 'Check laptop, mic, and webcam setup', completed: false },
          { id: 'dt-8', title: 'Check high-speed internet and backup hotspot', completed: false },
          { id: 'dt-9', title: 'Join meeting link 5 minutes early', completed: false },
        ],
        notes: 'Interview scheduled for tomorrow at 11:00 AM with Siddharth Mehta.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    mncCompanies: [
      {
        id: 'mnc-msft',
        companyName: 'Microsoft',
        locations: ['Bangalore', 'Hyderabad'],
        website: 'https://www.microsoft.com',
        careersUrl: 'https://careers.microsoft.com',
        targetRoles: ['Software Engineer', 'Full Stack Engineer'],
        priority: 'Top Priority',
        status: 'Target',
        notes: 'Targeting Cloud & Enterprise division. Preparing system design and DSA.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'mnc-amazon',
        companyName: 'Amazon',
        locations: ['Chennai', 'Bangalore'],
        website: 'https://www.amazon.com',
        careersUrl: 'https://amazon.jobs',
        targetRoles: ['SDE I', 'SDE II', 'Frontend Engineer'],
        priority: 'High',
        status: 'Applied',
        notes: 'Applied via employee referral for Chennai campus. Leadership principles prepared.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'mnc-accenture',
        companyName: 'Accenture',
        locations: ['Chennai', 'Pune'],
        website: 'https://www.accenture.com',
        careersUrl: 'https://www.accenture.com/in-en/careers',
        targetRoles: ['Custom Software Development Specialist', 'React Developer'],
        priority: 'Medium',
        status: 'Target',
        notes: 'Massive scale enterprise projects. Good work-life balance.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'mnc-google',
        companyName: 'Google',
        locations: ['Bangalore', 'Hyderabad'],
        website: 'https://www.google.com',
        careersUrl: 'https://careers.google.com',
        targetRoles: ['Software Engineer - Full Stack'],
        priority: 'Top Priority',
        status: 'Researching',
        notes: 'Need 100+ LeetCode problems solved before applying. Target Q4.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'mnc-oracle',
        companyName: 'Oracle',
        locations: ['Bangalore', 'Hyderabad'],
        website: 'https://www.oracle.com',
        careersUrl: 'https://www.oracle.com/corporate/careers',
        targetRoles: ['Applications Developer (MERN / React)'],
        priority: 'High',
        status: 'Ready to Apply',
        notes: 'Good match for Cloud ERP applications team.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }
    ],
    goals: [
      {
        id: 'goal-1',
        name: 'Apply to 10 jobs this week',
        category: 'Applications',
        targetValue: 10,
        currentValue: 6,
        unit: 'jobs',
        deadline: nextWeekStr,
        status: 'In Progress',
        notes: '4 more applications to go on LinkedIn and Naukri.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'goal-2',
        name: 'Complete 5 mock interviews',
        category: 'Interviews',
        targetValue: 5,
        currentValue: 3,
        unit: 'interviews',
        deadline: getFutureDateString(14),
        status: 'In Progress',
        notes: '2 peer mocks and 1 Pramp interview done.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'goal-3',
        name: 'Finish Node.js & Redis revision',
        category: 'Skill Prep',
        targetValue: 100,
        currentValue: 80,
        unit: '%',
        deadline: tomorrowStr,
        status: 'In Progress',
        notes: 'Review BullMQ worker threads and Redis cluster architecture.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'goal-4',
        name: 'Apply to 5 MNCs',
        category: 'MNC',
        targetValue: 5,
        currentValue: 2,
        unit: 'companies',
        deadline: getFutureDateString(20),
        status: 'In Progress',
        notes: 'Amazon applied, Microsoft and Oracle next.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'goal-5',
        name: 'Complete 20 technical questions',
        category: 'Skill Prep',
        targetValue: 20,
        currentValue: 14,
        unit: 'questions',
        deadline: nextWeekStr,
        status: 'In Progress',
        notes: 'LeetCode Medium array and string problems.',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  };
};
