import { DashboardData, ChecklistTemplate } from '../types';

export const BUILT_IN_TEMPLATES: ChecklistTemplate[] = [
  {
    id: 'tpl-interview-prep',
    name: 'Interview Preparation',
    description: 'Comprehensive pre-interview readiness checklist',
    category: 'Preparation',
    isBuiltIn: true,
    defaultItems: [
      { title: 'Company research & product offerings', priority: 'High', description: 'Understand mission, clients, tech stack, and recent news' },
      { title: 'Job description review & key requirements alignment', priority: 'High', description: 'Map your skills to each requirement in the JD' },
      { title: 'Resume review & project story recap', priority: 'High', description: 'Be ready to explain any point on your resume' },
      { title: 'Self introduction practice (Elevator Pitch)', priority: 'High', description: 'Practice a punchy 90-second intro focusing on your MERN expertise' },
      { title: 'Project explanation (Architecture, challenges, solutions)', priority: 'High', description: 'Deep dive into your key portfolio projects and system design' },
      { title: 'Technical preparation & core concepts', priority: 'High', description: 'Async JS, Event Loop, React Lifecycle, Node streams, indexing' },
      { title: 'Expected questions & behavioral stories (STAR method)', priority: 'Medium', description: 'Prepare for conflict resolution, leadership, and debugging scenarios' },
      { title: 'Questions for interviewer (Role, engineering culture, tech debt)', priority: 'Medium', description: 'Prepare 3-4 insightful questions' },
      { title: 'Salary discussion preparation & market rates', priority: 'Low', description: 'Know your minimum acceptable and target range' },
      { title: 'Interview setup check (Laptop, mic, camera, quiet space)', priority: 'High', description: 'Test Zoom/Meet 30 minutes before time' },
    ],
  },
  {
    id: 'tpl-technical-interview-mern',
    name: 'Technical Interview (MERN Stack)',
    description: 'Targeted technical revision checklist tailored to JavaScript, TypeScript, React, and Node.js',
    category: 'Technical',
    isBuiltIn: true,
    defaultItems: [
      { title: 'JavaScript fundamentals (Closures, Prototype, Event Loop, Promises, Async/Await)', priority: 'High' },
      { title: 'TypeScript (Generics, Interfaces vs Types, Utility types, Type Narrowing)', priority: 'High' },
      { title: 'React (Hooks, Custom Hooks, Context, Reconciliation, Memoization, State management)', priority: 'High' },
      { title: 'Node.js & Express (Event-driven architecture, Middleware, Streams, Clustering, Error handling)', priority: 'High' },
      { title: 'REST APIs & Best Practices (Status codes, Versioning, Idempotency, Rate limiting)', priority: 'High' },
      { title: 'Authentication & Security (JWT, Refresh tokens, OAuth, CORS, SQL/NoSQL injection prevention)', priority: 'High' },
      { title: 'MongoDB & Mongoose (Aggregations, Schema design, Indexing performance, Sharding basics)', priority: 'High' },
      { title: 'MySQL & Relational DBs (ACID properties, Joins, Normalization, Query optimization)', priority: 'Medium' },
      { title: 'Redis & BullMQ (Caching strategies, Pub/Sub, Queue processing, Rate limiting)', priority: 'Medium' },
      { title: 'Coding Practice (Arrays, Strings, Hash maps, Two pointers, Recursion)', priority: 'High' },
      { title: 'System Design Basics (Scalability, Load balancing, Microservices vs Monolith, CDN)', priority: 'Medium' },
      { title: 'Project Deep Dive: Architecture, trade-offs, and scaling decisions', priority: 'High' },
    ],
  },
  {
    id: 'tpl-hr-interview',
    name: 'HR & Behavioral Interview',
    description: 'Key behavioral questions and cultural fit evaluation',
    category: 'HR',
    isBuiltIn: true,
    defaultItems: [
      { title: 'Why do you want to join this company?', priority: 'High' },
      { title: 'Why are you looking for a change / next career step?', priority: 'High' },
      { title: 'Strengths and areas of growth with real examples', priority: 'Medium' },
      { title: 'Time when you handled a difficult deadline or production bug', priority: 'High' },
      { title: 'Handling disagreement with team member or manager', priority: 'Medium' },
      { title: 'Notice period, current CTC, expected CTC, and location flexibility', priority: 'High' },
      { title: 'Inquiring about company culture, team hierarchy, and mentorship', priority: 'Medium' },
    ],
  },
  {
    id: 'tpl-before-applying',
    name: 'Before Applying Checklist',
    description: 'Pre-flight check before clicking Submit on any job portal',
    category: 'Application',
    isBuiltIn: true,
    defaultItems: [
      { title: 'Tailor resume keywords to job description', priority: 'High' },
      { title: 'Verify GitHub repositories and live demo links are online', priority: 'High' },
      { title: 'Check LinkedIn profile headline and experience alignment', priority: 'Medium' },
      { title: 'Identify recruiter or team lead on LinkedIn for referral message', priority: 'Medium' },
      { title: 'Prepare customized cover note or cold message', priority: 'Medium' },
      { title: 'Track in CareerHub dashboard immediately', priority: 'High' },
    ],
  },
];

export const getInitialEmptyData = (): DashboardData => {
  return {
    version: 2,
    lastUpdated: new Date().toISOString(),
    userProfile: {
      name: 'Full Stack Engineer',
      title: 'Full Stack Developer (MERN)',
      summary: 'Experienced with JavaScript, TypeScript, React, Node.js, Express, MongoDB, MySQL, Redis, BullMQ, and Docker.',
      skills: {
        languages: ['JavaScript', 'TypeScript', 'SQL', 'HTML5', 'CSS3'],
        frontend: ['React.js', 'Tailwind CSS', 'Bootstrap'],
        backend: ['Node.js', 'Express.js', 'REST APIs', 'JWT Authentication', 'BullMQ'],
        databases: ['MongoDB', 'MySQL', 'Redis', 'Mongoose'],
        cloudAndTools: ['AWS Basics', 'Docker', 'Git', 'GitHub', 'Postman', 'MongoDB Compass', 'Vercel', 'Render', 'npm'],
      },
      projects: [
        'FarmGuard — Agricultural Monitoring System',
        'Cartify — E-Commerce Marketplace',
        'Vendr — Full Stack E-Commerce Platform',
        'Smart Exam Proctoring System',
      ],
    },
    roles: [],
    applications: [],
    interviews: [],
    checklists: [],
    checklistTemplates: BUILT_IN_TEMPLATES,
    dayChecklists: [],
    mncCompanies: [],
    goals: [],
  };
};
